name = "Olympe Create"
author = "Helixire"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77cdb8a1eed7a9bf13a50737d1633fcf81407dae2b54007627f74b708d02900d"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
